version: "2"
services:
  mongo:
    container_name: mongo_ftc
    image: mongo
    volumes:
      - ./mdata:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: freetechcourses
    restart: always
    build: .
    ports: 
      - "80:3000"
    links:
      - mongo